# The Iris Dataset
The data set consists of 50 samples from each of three species of Iris (Iris setosa, Iris virginica and Iris versicolor). Four features were measured from each sample: the length and the width of the sepals and petals, in centimeters.

The dataset contains a set of 150 records under five attributes - petal length, petal width, sepal length, sepal width and species.

### Specifying the TensorFlow version
Running `import tensorflow` will import the default version (currently 1.x). You can use 2.x by running a cell with the `tensorflow_version` magic **before** you run `import tensorflow`.

In [31]:
%tensorflow_version 2.x #Take latest version of tensor flow

`%tensorflow_version` only switches the major version: `1.x` or `2.x`.
You set: `2.x #Take latest version of tensor flow`. This will be interpreted as: `2.x`.


TensorFlow is already loaded. Please restart the runtime to change versions.


### Import TensorFlow
Once you have specified a version via this magic, you can run `import tensorflow` as normal and verify which version was imported as follows:

In [32]:
import tensorflow as tf
print(tf.__version__) #check the latest version you are working in

2.0.0


### Set random seed

In [0]:
tf.random.set_seed(42)

## Question 1

### Import dataset
- Import iris dataset
- Import the dataset using sklearn library

In [0]:
import pandas as pd
import numpy as np
from sklearn import datasets
iris = datasets.load_iris()

In [9]:
iris #entire dataset is loaded as array

{'DESCR': '.. _iris_dataset:\n\nIris plants dataset\n--------------------\n\n**Data Set Characteristics:**\n\n    :Number of Instances: 150 (50 in each of three classes)\n    :Number of Attributes: 4 numeric, predictive attributes and the class\n    :Attribute Information:\n        - sepal length in cm\n        - sepal width in cm\n        - petal length in cm\n        - petal width in cm\n        - class:\n                - Iris-Setosa\n                - Iris-Versicolour\n                - Iris-Virginica\n                \n    :Summary Statistics:\n\n    ============== ==== ==== ======= ===== ====================\n                    Min  Max   Mean    SD   Class Correlation\n    ============== ==== ==== ======= ===== ====================\n    sepal length:   4.3  7.9   5.84   0.83    0.7826\n    sepal width:    2.0  4.4   3.05   0.43   -0.4194\n    petal length:   1.0  6.9   3.76   1.76    0.9490  (high!)\n    petal width:    0.1  2.5   1.20   0.76    0.9565  (high!)\n    ===========

## Question 2

### Get features and label from the dataset in separate variable
- you can get the features using .data method
- you can get the features using .target method

In [0]:
X = iris.data   #since the dataset itself is an inbuilt dictionary(in array format), we have the inner data split into feature data (X) and target data (Y), hence we split x and y directly
y = iris.target

## Question 3

### Create train and test data
- use train_test_split to get train and test set
- set a random_state
- test_size: 0.25

In [0]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X,y, test_size=.25, random_state=7)

## Question 4

### One-hot encode the labels
- convert class vectors (integers) to binary class matrix
- convert labels
- number of classes: 3
- we are doing this to use categorical_crossentropy as loss

In [0]:
y_train = tf.keras.utils.to_categorical(y_train, num_classes=3)
y_test = tf.keras.utils.to_categorical(y_test, num_classes=3) # Since the caterigocal variable, it denotes the number of outputs, 
                                                              #which need to get, for 3 categorical varibale 3 outputs we need to get,
                                                              # where 3 neurons - one for each here

In [38]:
y_test

array([[0., 0., 1.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.]], dtype=float32)

## Question 5

### Initialize a sequential model
- Define a sequential model

In [0]:
model = tf.keras.models.Sequential() 

## Question 6

### Add a layer
- Use Dense Layer  with input shape of 4 (according to the feature set) and number of outputs set to 3
- Apply Softmax on Dense Layer outputs

In [0]:
model.add(tf.keras.layers.Dense(3, input_shape=(4,), activation='softmax')) #3 defines the number of outputs, number of neuron in the last layer as the number of categorical variable is 3

## Question 7

### Compile the model
- Use SGD as Optimizer
- Use categorical_crossentropy as loss function
- Use accuracy as metrics

In [0]:
model.compile(optimizer='sgd', loss='categorical_crossentropy', metrics=['accuracy']) 

## Question 8

### Summarize the model
- Check model layers
- Understand number of trainable parameters

In [42]:
model.summary() #earlier 5 results came because the cell has been executed 5 times, 15 params is 4 cols 3 catergocial variable, 4*3 = 12 and 3 bias(number of neurons)

Model: "sequential_2"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_5 (Dense)              (None, 3)                 15        
Total params: 15
Trainable params: 15
Non-trainable params: 0
_________________________________________________________________


## Question 9

### Fit the model
- Give train data as training features and labels
- Epochs: 100
- Give validation data as testing features and labels

In [43]:
model.fit(X_train, y_train, validation_data=(X_test, y_test), epochs=100,
          batch_size = X_train.shape[0])       #X_train, X_test, y_train, y_test 

Train on 112 samples, validate on 38 samples
Epoch 1/100
112/112 [==============================] - 0s 3ms/sample - loss: 3.1426 - accuracy: 0.3482 - val_loss: 2.8766 - val_accuracy: 0.2895
Epoch 2/100
112/112 [==============================] - 0s 140us/sample - loss: 2.7259 - accuracy: 0.3482 - val_loss: 2.4734 - val_accuracy: 0.2895
Epoch 3/100
112/112 [==============================] - 0s 127us/sample - loss: 2.3545 - accuracy: 0.3482 - val_loss: 2.1354 - val_accuracy: 0.2895
Epoch 4/100
112/112 [==============================] - 0s 129us/sample - loss: 2.0456 - accuracy: 0.3482 - val_loss: 1.8736 - val_accuracy: 0.2895
Epoch 5/100
112/112 [==============================] - 0s 133us/sample - loss: 1.8090 - accuracy: 0.3482 - val_loss: 1.6840 - val_accuracy: 0.2895
Epoch 6/100
112/112 [==============================] - 0s 138us/sample - loss: 1.6395 - accuracy: 0.3482 - val_loss: 1.5509 - val_accuracy: 0.2632
Epoch 7/100
112/112 [==============================] - 0s 126us/sample - lo

## Question 10

### Make predictions
- Predict labels on one row

In [46]:
y_predict=model.predict(X_test[0:1])
y_predict   #[0.10935906, 0.37774706, 0.51289386] - 0.5 is the highest value hence the predicted values is 0.5 the highest value hence the predicted class 
            #is 2[0,1,2] for the first row
            # hence the y_Test is projected as [0,0,1]
            #Incase if [0.10935906, 0.51289386,0.37774706] - 0.5 is the highest hence the predicted values is 0.5 the highest value hence the predicted class 
            #will be as 1[0,1,2] for the first row
            # hence the y_Test is projected as [0,1,0]

array([[0.10935906, 0.37774706, 0.51289386]], dtype=float32)

In [47]:
y_predict=model.predict_classes(X_test[0:1])
y_predict

array([2])

In [48]:
y_test[0:1]

array([[0., 0., 1.]], dtype=float32)

### Compare the prediction with actual label
- Print the same row as done in the previous step but of actual labels

In [45]:
y_test[0:1]

array([[0., 0., 1.]], dtype=float32)



---



# Stock prices dataset
The data is of tock exchange's stock listings for each trading day of 2010 to 2016.

## Description
A brief description of columns.
- open: The opening market price of the equity symbol on the date
- high: The highest market price of the equity symbol on the date
- low: The lowest recorded market price of the equity symbol on the date
- close: The closing recorded price of the equity symbol on the date
- symbol: Symbol of the listed company
- volume: Total traded volume of the equity symbol on the date
- date: Date of record

### Specifying the TensorFlow version
Running `import tensorflow` will import the default version (currently 1.x). You can use 2.x by running a cell with the `tensorflow_version` magic **before** you run `import tensorflow`.

In [0]:
%tensorflow_version 2.x

### Import TensorFlow
Once you have specified a version via this magic, you can run `import tensorflow` as normal and verify which version was imported as follows:

In [50]:
import tensorflow as tf
print(tf.__version__)

2.0.0


### Set random seed

In [0]:
tf.random.set_seed(42)

## Question 1

### Load the data
- load the csv file and read it using pandas
- file name is prices.csv

In [52]:
# run this cell to upload file if you are using google colab
from google.colab import files
files.upload()

MessageError: ignored

In [53]:
from google.colab import drive
drive.mount('/content/gdrive')

Go to this URL in a browser: https://accounts.google.com/o/oauth2/auth?client_id=947318989803-6bn6qk8qdgf4n4g3pfee6491hc0brc4i.apps.googleusercontent.com&redirect_uri=urn%3aietf%3awg%3aoauth%3a2.0%3aoob&response_type=code&scope=email%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdocs.test%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdrive%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdrive.photos.readonly%20https%3a%2f%2fwww.googleapis.com%2fauth%2fpeopleapi.readonly

Enter your authorization code:
··········
Mounted at /content/gdrive


In [0]:
import pandas as pd
import numpy as np
df1 = pd.read_csv('gdrive/My Drive/AIML/prices.csv')

In [56]:
df1.head()

date symbol        open  ...         low        high     volume
0  2016-01-05 00:00:00   WLTW  123.430000  ...  122.309998  126.250000  2163600.0
1  2016-01-06 00:00:00   WLTW  125.239998  ...  119.940002  125.540001  2386400.0
2  2016-01-07 00:00:00   WLTW  116.379997  ...  114.930000  119.739998  2489500.0
3  2016-01-08 00:00:00   WLTW  115.480003  ...  113.500000  117.440002  2006300.0
4  2016-01-11 00:00:00   WLTW  117.010002  ...  114.089996  117.330002  1408600.0

[5 rows x 7 columns]

## Question 2

### Drop columnns
- drop "date" and "symbol" column from the data

In [0]:
df2 = df1.drop(['date','symbol'],axis = 1)

## Question 3

### Take initial rows
- Take first 1000 rows from the data
- This step is done to make the execution faster

In [0]:
df3 = df2.head(1000)

In [62]:
df3.shape

(1000, 5)

## Question 4

### Get features and label from the dataset in separate variable
- Take "open", "close", "low", "high" columns as features
- Take "volume" column as label
- Normalize label column by dividing it with 1000000

In [0]:
features = df3.drop("volume",axis=1)          #feature set
label = df3[["volume"]] /1000000

In [65]:
label.head()

volume
0  2.1636
1  2.3864
2  2.4895
3  2.0063
4  1.4086

## Question 5

### Convert data
- Convert features and labels to numpy array
- Convert their data type to "float32"

In [0]:
features = features.values
label = label.values

In [0]:
features = features.astype('float32')
label = label.astype('float32')

In [74]:
features.dtypes

AttributeError: ignored

In [75]:
label.dtypes

AttributeError: ignored

## Question 6

### Normalize data
- Normalize features
- Use tf.math.l2_normalize to normalize features
- You can read more about it here https://www.tensorflow.org/api_docs/python/tf/math/l2_normalize

In [0]:
features = tf.math.l2_normalize(features)

## Question 7

### Define weight and bias
- Initialize weight and bias with tf.zeros
- tf.zeros is an initializer that generates tensors initialized to 0
- Specify the value for shape

In [0]:
w = tf.zeros(shape=(4, 1))
b = tf.zeros(shape=(1)) # this itself assigns the bias accodring to the number of neuron you define

## Question 8

### Get prediction
- Define a function to get prediction
- Approach: prediction = (X * W) + b; here is X is features

In [0]:
@tf.function
def prediction(features, w, b):
    y_pred = tf.add(tf.matmul(features, w), b)
    return y_pred

### Calculate loss
- Calculate loss using predictions
- Define a function to calculate loss
- We are calculating mean squared error

In [0]:
@tf.function
def loss(y_actual, y_predicted):
    diff = y_actual - y_predicted
    sqr = tf.square(diff)
    avg = tf.reduce_mean(sqr)
    return avg

## Question 9

### Define a function to train the model
1.   Record all the mathematical steps to calculate Loss
2.   Calculate Gradients of Loss w.r.t weights and bias
3.   Update Weights and Bias based on gradients and learning rate to minimize loss

In [0]:
@tf.function
def train(x, y_actual, w, b, learning_rate=0.01):
    
    # Record mathematical operations on 'tape' to calculate loss
    with tf.GradientTape() as t:
        t.watch([w,b])
        current_prediction = prediction(x, w, b)
        current_loss = loss(y_actual, current_prediction)
    
    # Calculate Gradients for Loss with respect to Weights and Bias
    dw, db = t.gradient(current_loss,[w, b])
    
    # Update Weights and Bias
    w = w - learning_rate * dw
    b = b - learning_rate * db
    
    return w, b

## Question 10

### Train the model for 100 epochs 
- Observe the training loss at every iteration

In [97]:
for i in range(100):    
    w, b = train(features, label, w, b)
    print('Current Training Loss on iteration', i, loss(label, prediction(features, w, b)).numpy())

Current Training Loss on iteration 0 236.16805
Current Training Loss on iteration 1 235.09369
Current Training Loss on iteration 2 234.06194
Current Training Loss on iteration 3 233.07103
Current Training Loss on iteration 4 232.1194
Current Training Loss on iteration 5 231.20547
Current Training Loss on iteration 6 230.32773
Current Training Loss on iteration 7 229.48479
Current Training Loss on iteration 8 228.67525
Current Training Loss on iteration 9 227.89775
Current Training Loss on iteration 10 227.1511
Current Training Loss on iteration 11 226.43398
Current Training Loss on iteration 12 225.7453
Current Training Loss on iteration 13 225.08394
Current Training Loss on iteration 14 224.4487
Current Training Loss on iteration 15 223.83865
Current Training Loss on iteration 16 223.25282
Current Training Loss on iteration 17 222.69019
Current Training Loss on iteration 18 222.14984
Current Training Loss on iteration 19 221.6309
Current Training Loss on iteration 20 221.13252
Current

### Observe values of Weight
- Print the updated values

In [98]:
w.numpy()

array([[0.0194333 ],
       [0.01969694],
       [0.01937149],
       [0.01976266]], dtype=float32)

### Observe values of Bias
- Print the updated values

In [99]:
b.numpy()

array([4.608607], dtype=float32)